add QPS meterics
go-chassis/go-chassis pull request #1061
Opened 2022-08-17 02:55 UTC by kkf1

增加QPS的监控指标

2022-08-17 07:39 UTC, tianxiaoliang commented
为何在业务进程里做QPS的计算

2022-08-18 03:14 UTC, tianxiaoliang commented on pkg/metrics/metrics_test.go
>  		"service": "s",
用t.Run隔离

2022-08-18 11:38 UTC, little-cui requested changes

2022-08-18 11:41 UTC, kkf1 commented on pkg/metrics/metrics_test.go
>  		"service": "s",
done

2022-08-18 11:44 UTC, kkf1 commented on pkg/metrics/prometheus.go
> +func Gather() ([]*dto.MetricFamily, error) {
done

2022-08-18 14:06 UTC, tianxiaoliang approved these changes

2022-08-18 14:06 UTC, merged